[package]
name = "bathbot-model"
version = "0.1.0"
edition = "2021"

[dependencies]
bathbot-util = { path = "../bathbot-util" }
bitflags = { version = "1.0" }
eyre = { version = "0.6" }
http = { version = "0.2" }
leaky-bucket-lite = { version = "0.5", features = ["parking_lot"] }
once_cell = { version = "1.0" }
rosu-v2 = { git = "https://github.com/MaxOhn/rosu-v2", branch = "next", features = ["cache", "metrics", "rkyv"] }
rkyv = { version = "0.7" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = { version = "1.0" }
time = { version = "0.3", features = ["parsing"] }
twilight-interactions = { git = "https://github.com/MaxOhn/twilight-interactions", branch = "rkyv-15", default-features = false, features = ["derive"] }
twilight-model = { git = "https://github.com/MaxOhn/twilight", branch = "rkyv-15", default-features = false }

# twilight-interactions = { path = "../../twilight-interactions/twilight-interactions", default-features = false, features = ["derive"] }
# twilight-model = { path = "../../twilight/twilight-model", default-features = false }