# https://rust-lang.github.io/rustfmt/

edition = "2021"
newline_style = "Unix"
use_field_init_shorthand = true

# nightly configs
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
wrap_comments = true