use crate::{util::CowUtils, Context};

use smallstr::SmallString;
use std::{borrow::Borrow, fmt, ops::Deref};

#[derive(Clone, Debug, Eq, PartialEq, Hash)]
pub struct CountryCode(SmallString<[u8; 2]>);

impl CountryCode {
    // TODO: Benchmark using HashMap
    pub fn from_name(name: &str) -> Option<Self> {
        let code = match name.cow_to_ascii_lowercase().as_ref() {
            "afghanistan" => "AF",
            "albania" => "AL",
            "algeria" => "DZ",
            "american samoa" => "AS",
            "andorra" => "AD",
            "angola" => "AO",
            "anguilla" => "AI",
            "antarctica" => "AQ",
            "antigua" | "barbuda" => "AG",
            "argentina" => "AR",
            "armenia" => "AM",
            "aruba" => "AW",
            "australia" => "AU",
            "austria" => "AT",
            "azerbaijan" => "AZ",
            "bahamas" => "BS",
            "bahrain" => "BH",
            "bangladesh" => "BD",
            "barbados" => "BB",
            "belarus" => "BY",
            "belgium" => "BE",
            "belize" => "BZ",
            "benin" => "BJ",
            "bermuda" => "BM",
            "bhutan" => "BT",
            "bolivia" => "BO",
            "bonaire" | "sint eustatius" | "saba" => "BQ",
            "bosnia and herzegovina" => "BA",
            "botswana" => "BW",
            "bouvet island" => "BV",
            "brazil" => "BR",
            "british indian ocean territory" => "IO",
            "brunei darussalam" => "BN",
            "bulgaria" => "BG",
            "burkina faso" => "BF",
            "burundi" => "BI",
            "cabo verde" => "CV",
            "cambodia" => "KH",
            "cameroon" => "CM",
            "canada" => "CA",
            "cayman islands" => "KY",
            "central african republic" => "CF",
            "chad" => "TD",
            "chile" => "CL",
            "china" => "CN",
            "christmas island" => "CX",
            "cocos islands" => "CC",
            "colombia" => "CO",
            "comoros" => "KM",
            "cemocratic republic of congo" => "CD",
            "congo" => "CG",
            "cook islands" => "CK",
            "costa rica" => "CR",
            "croatia" => "HR",
            "cuba" => "CU",
            "curaçao" => "CW",
            "cyprus" => "CY",
            "czechia" => "CZ",
            "côte d'ivoire" => "CI",
            "denmark" => "DK",
            "djibouti" => "DJ",
            "dominica" => "DM",
            "dominican republic" => "DO",
            "ecuador" => "EC",
            "egypt" => "EG",
            "el salvador" => "SV",
            "equatorial guinea" => "GQ",
            "eritrea" => "ER",
            "estonia" => "EE",
            "eswatini" => "SZ",
            "ethiopia" => "ET",
            "falkland islands" | "malvinas" => "FK",
            "faroe islands" => "FO",
            "fiji" => "FJ",
            "finland" => "FI",
            "france" => "FR",
            "french guiana" => "GF",
            "french polynesia" => "PF",
            "french southern territories" => "TF",
            "gabon" => "GA",
            "gambia" => "GM",
            "georgia" => "GE",
            "germany" => "DE",
            "ghana" => "GH",
            "gibraltar" => "GI",
            "greece" => "GR",
            "greenland" => "GL",
            "grenada" => "GD",
            "guadeloupe" => "GP",
            "guam" => "GU",
            "guatemala" => "GT",
            "guernsey" => "GG",
            "guinea" => "GN",
            "guinea-bissau" => "GW",
            "guyana" => "GY",
            "haiti" => "HT",
            "heard island" | "mcdonald islands" => "HM",
            "holy see" => "VA",
            "honduras" => "HN",
            "hong Kong" => "HK",
            "hungary" => "HU",
            "iceland" => "IS",
            "india" => "IN",
            "indonesia" => "ID",
            "iran" => "IR",
            "iraq" => "IQ",
            "ireland" => "IE",
            "isle of man" => "IM",
            "israel" => "IL",
            "italy" => "IT",
            "jamaica" => "JM",
            "japan" => "JP",
            "jersey" => "JE",
            "jordan" => "JO",
            "kazakhstan" => "KZ",
            "kenya" => "KE",
            "kiribati" => "KI",
            "north korea" => "KP",
            "south korea" => "KR",
            "kuwait" => "KW",
            "kyrgyzstan" => "KG",
            "lao people's democratic republic" => "LA",
            "latvia" => "LV",
            "lebanon" => "LB",
            "lesotho" => "LS",
            "liberia" => "LR",
            "libya" => "LY",
            "liechtenstein" => "LI",
            "lithuania" => "LT",
            "luxembourg" => "LU",
            "macao" => "MO",
            "madagascar" => "MG",
            "malawi" => "MW",
            "malaysia" => "MY",
            "maldives" => "MV",
            "mali" => "ML",
            "malta" => "MT",
            "marshall islands" => "MH",
            "martinique" => "MQ",
            "mauritania" => "MR",
            "mauritius" => "MU",
            "mayotte" => "YT",
            "mexico" => "MX",
            "micronesia" => "FM",
            "moldova" => "MD",
            "monaco" => "MC",
            "mongolia" => "MN",
            "montenegro" => "ME",
            "montserrat" => "MS",
            "morocco" => "MA",
            "mozambique" => "MZ",
            "myanmar" => "MM",
            "namibia" => "NA",
            "nauru" => "NR",
            "nepal" => "NP",
            "the netherlands" | "netherlands" => "NL",
            "new caledonia" => "NC",
            "new zealand" => "NZ",
            "nicaragua" => "NI",
            "niger" => "NE",
            "nigeria" => "NG",
            "niue" => "NU",
            "norfolk island" => "NF",
            "northern mariana islands" => "MP",
            "norway" => "NO",
            "oman" => "OM",
            "pakistan" => "PK",
            "palau" => "PW",
            "palestine" => "PS",
            "panama" => "PA",
            "papua new guinea" => "PG",
            "paraguay" => "PY",
            "peru" => "PE",
            "philippines" => "PH",
            "pitcairn" => "PN",
            "poland" => "PL",
            "portugal" => "PT",
            "puerto rico" => "PR",
            "qatar" => "QA",
            "north macedonia" => "MK",
            "romania" => "RO",
            "russian federation" => "RU",
            "rwanda" => "RW",
            "réunion" => "RE",
            "saint barthélemy" => "BL",
            "saint helena" => "SH",
            "saint kitts and nevis" => "KN",
            "saint lucia" => "LC",
            "saint martin" => "MF",
            "saint pierre" | "miquelon" => "PM",
            "saint vincent" | "grenadines" => "VC",
            "samoa" => "WS",
            "san marino" => "SM",
            "sao tome and principe" => "ST",
            "saudi arabia" => "SA",
            "senegal" => "SN",
            "serbia" => "RS",
            "seychelles" => "SC",
            "sierra leone" => "SL",
            "singapore" => "SG",
            "sint maarten" => "SX",
            "slovakia" => "SK",
            "slovenia" => "SI",
            "solomon islands" => "SB",
            "somalia" => "SO",
            "south africa" => "ZA",
            "south georgia" | "south sandwich islands" => "GS",
            "south sudan" => "SS",
            "spain" => "ES",
            "sri lanka" => "LK",
            "sudan" => "SD",
            "suriname" => "SR",
            "svalbard" | "jan mayen" => "SJ",
            "sweden" => "SE",
            "switzerland" => "CH",
            "syrian arab republic" => "SY",
            "taiwan" => "TW",
            "tajikistan" => "TJ",
            "tanzania" => "TZ",
            "thailand" => "TH",
            "timor-leste" => "TL",
            "togo" => "TG",
            "tokelau" => "TK",
            "tonga" => "TO",
            "trinidad and tobago" => "TT",
            "tunisia" => "TN",
            "turkey" => "TR",
            "turkmenistan" => "TM",
            "turks and caicos islands" => "TC",
            "tuvalu" => "TV",
            "uganda" => "UG",
            "ukraine" => "UA",
            "united arab emirates" => "AE",
            "united kingdom" | "uk" | "great britain" => "GB",
            "united states minor outlying islands" => "UM",
            "united states of america" | "usa" | "united states" => "US",
            "uruguay" => "UY",
            "uzbekistan" => "UZ",
            "vanuatu" => "VU",
            "venezuela " => "VE",
            "viet nam" => "VN",
            "virgin islands (british)" => "VG",
            "virgin islands (u.s.)" => "VI",
            "wallis and futuna" => "WF",
            "western sahara" => "EH",
            "yemen" => "YE",
            "zambia" => "ZM",
            "zimbabwe" => "ZW",
            _ => return None,
        };

        Some(Self(code.into()))
    }

    pub fn snipe_supported(&self, ctx: &Context) -> bool {
        ctx.contains_country(self.0.as_str())
    }
}

impl Deref for CountryCode {
    type Target = SmallString<[u8; 2]>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl From<String> for CountryCode {
    fn from(code: String) -> Self {
        Self(code.into())
    }
}

impl From<&str> for CountryCode {
    fn from(code: &str) -> Self {
        Self(code.into())
    }
}

impl Borrow<str> for CountryCode {
    fn borrow(&self) -> &str {
        self.0.as_str()
    }
}

impl fmt::Display for CountryCode {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}
