CREATE TABLE role_assign (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    guild BIGINT UNSIGNED NOT NULL,
    channel BIGINT UNSIGNED NOT NULL,
    message BIGINT UNSIGNED NOT NULL,
    role BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (id)
)