CREATE TABLE maps (
    beatmap_id INT UNSIGNED NOT NULL,
    beatmapset_id INT UNSIGNED NOT NULL,
    mode TINYINT UNSIGNED NOT NULL,
    version VARCHAR(128) NOT NULL,
    seconds_drain INT UNSIGNED NOT NULL,
    seconds_total INT UNSIGNED NOT NULL,
    bpm FLOAT NOT NULL,
    stars FLOAT NOT NULL,
    diff_cs FLOAT NOT NULL,
    diff_od FLOAT NOT NULL,
    diff_ar FLOAT NOT NULL,
    diff_hp FLOAT NOT NULL,
    count_circle INT UNSIGNED NOT NULL,
    count_slider INT UNSIGNED NOT NULL,
    count_spinner INT UNSIGNED NOT NULL,
    max_combo INT UNSIGNED,
    PRIMARY KEY (beatmap_id),
    FOREIGN KEY (beatmapset_id) REFERENCES mapsets(beatmapset_id)
)