CREATE TABLE beatmaps_pp (
    beatmap_id INT UNSIGNED PRIMARY KEY,
    NM FLOAT NOT NULL,
    HD FLOAT NOT NULL,
    HR FLOAT NOT NULL,
    DT FLOAT NOT NULL,
    EZ FLOAT NOT NULL,
    NF FLOAT NOT NULL,
    HDHR FLOAT NOT NULL,
    HDDT FLOAT NOT NULL
)